name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I -L \
          -A "Mozilla/5.0" \
          --retry 5 \
          --retry-all-errors \
          https://mhf-civil-calc.streamlit.app/
